/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AStudentManage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import CTemporal.temp;
import java.sql.ResultSet;

/**
 *
 * @author Dr. Alkaloid Wells
 */
public class DRegistrationForm extends javax.swing.JFrame {

    /**
     * Creates new form DLectureRegistrationForm
     */
    public DRegistrationForm() {
        initComponents();
        System.out.println(temp.flag1);
    }
      Connection con;
      PreparedStatement pst;
      Connection con1;
      PreparedStatement pst1;
      ResultSet rs;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSex = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPob = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPads = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtDoo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtRoo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNa = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMstatus = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Personal Information");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(415, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("YouNiversity");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("A:\\Project 2021.2022.sim1\\SDT\\bg_036.jpg")); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 340));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 96, 140, 340));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel3.setText("SURNAME*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 118, -1, -1));
        jPanel1.add(txtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 137, 162, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel6.setText("SEX");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, -1, -1));

        txtSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));
        jPanel1.add(txtSex, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 175, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel4.setText("DATE OF BIRTH*");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 168, -1, -1));

        txtDob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDobActionPerformed(evt);
            }
        });
        jPanel1.add(txtDob, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 187, 162, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel8.setText("PLACE OF BIRTH");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, 20));
        jPanel1.add(txtPob, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 175, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel5.setText("PARENT NAME");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 218, -1, -1));
        jPanel1.add(txtPname, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 237, 162, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel7.setText("PARENT ADRESS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        txtPads.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPadsActionPerformed(evt);
            }
        });
        jPanel1.add(txtPads, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 175, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel9.setText("DIVISION OF ORIGIN");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 263, -1, -1));
        jPanel1.add(txtDoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 282, 162, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel10.setText("REGION OF ORIGINE");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, -1, -1));

        txtRoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRooActionPerformed(evt);
            }
        });
        jPanel1.add(txtRoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, 175, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setText("NATIONALITY*");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 320, -1, -1));
        jPanel1.add(txtNa, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 339, 162, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel12.setText("MARITAL STATUS");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, -1, 20));

        txtMstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Married" }));
        jPanel1.add(txtMstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 340, 175, -1));

        jButton1.setText("NEXT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 87, 37));

        jButton2.setText("BACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 84, 37));

        jLabel13.setIcon(new javax.swing.ImageIcon("A:\\Project 2021.2022.sim1\\SDT\\bg_035.jpg")); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 580, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDobActionPerformed

    private void txtPadsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPadsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPadsActionPerformed

    private void txtRooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRooActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            int LoidFk;
            LoidFk = temp.LOID;
            String surname = txtSname.getText();
            String sex = txtSex.getSelectedItem().toString();
            String dob = txtDob.getText();
            String pob = txtPob.getText();
            String parentname = txtPname.getText();
            String nationality = txtPads.getText();
            String doo = txtDoo.getText();
            String roo = txtRoo.getText();
            String parentadd = txtNa.getText();
            String mstatu = txtMstatus.getSelectedItem().toString();

            // TODO add your handling code here:

            if(txtSname.getText().length()== 0 || txtDob.getText().length()== 0 || txtPob.getText().length()== 0 || txtDoo.getText().length()== 0||txtRoo.getText().length()== 0|| txtNa.getText().length()== 0)
            {
                JOptionPane.showMessageDialog(this, "Missing Section Or Department ");
            }

            else
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("insert into studentinfo(LOID, surname, sex, dob, pob, parentname, parentadd,doo, roo, nation, mstatu)values(?, ?,?, ?,?, ?,?, ?,?, ?, ?)");
                pst.setInt(1, LoidFk);
                pst.setString(2, surname);
                pst.setString(3, sex);
                pst.setString(4, dob);
                pst.setString(5, pob);
                pst.setString(6, parentname);
                pst.setString(7, parentadd);
                pst.setString(8, doo);
                pst.setString(9, roo);
                pst.setString(10, nationality);
                pst.setString(11, mstatu);
                pst.executeUpdate();
                 
                pst1 = con.prepareStatement("select  * from studentinfo where LOID = ? and surname = ?");
                pst1.setInt(1, LoidFk);
                pst1.setString(2, surname);
                rs = pst1.executeQuery();
            
                 if (rs.next())
                 {
                     temp.SID = rs.getInt("ID");
                 }
                 
                int y = temp.flag1;
                if(y == 7)
                    {  
                       ESchoolSelectS m = new ESchoolSelectS();
                        this.hide();  
                        m.setVisible(true);
                         
                     }
                     else if(y == 8)
                     {  
                         
                         ESchoolSelectL m = new ESchoolSelectL();
                         this.hide();  
                         m.setVisible(true);
                         
                     }
                     else 
                     {
                         JOptionPane.showMessageDialog(this, "No Application Found");
                     }
            
        }
            // TODO add your handling code here:
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(DRegistrationForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         BLogin m = new BLogin();
         this.hide();
         m.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DRegistrationForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtDoo;
    private javax.swing.JComboBox<String> txtMstatus;
    private javax.swing.JTextField txtNa;
    private javax.swing.JTextField txtPads;
    private javax.swing.JTextField txtPname;
    private javax.swing.JTextField txtPob;
    private javax.swing.JTextField txtRoo;
    private javax.swing.JComboBox<String> txtSex;
    private javax.swing.JTextField txtSname;
    // End of variables declaration//GEN-END:variables
}
