/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AStudentManage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
/**
 *
 * @author Dr. Alkaloid Wells
 */
public class JSAdmin extends javax.swing.JFrame {

    /**
     * Creates new form JSAdmin
     */
    public JSAdmin() {
        initComponents();
    }
    Connection con;
    PreparedStatement pst;
     ResultSet rs;
     ResultSetMetaData rss;
     DefaultTableModel Df;
     Connection con1;
     PreparedStatement pst1;
     ResultSet rs1;
     Connection con2;
     PreparedStatement pst2;
     ResultSet rs2;
     
                 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        txtSec = new javax.swing.JComboBox<>();
        txtDep = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        admin1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 102));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adminstrator BOX");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Q1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 89, -1));

        jButton2.setText("Q2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 89, -1));

        jButton3.setText("Q3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 89, -1));

        jButton4.setText("Q4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 89, -1));

        jButton5.setText("Q5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 89, -1));

        jButton6.setText("Q6");
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 89, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Option1");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 45, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Option 2");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 94, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Option3");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 143, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Option4");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 199, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Option5");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Option 6");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Option 7");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jButton7.setText("Q7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 89, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 51, 102));
        jLabel19.setText("YouNiversity");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        txtSec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Basic Technica ", "OrdinaryTechnical ", "Higher Technical " }));
        txtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecActionPerformed(evt);
            }
        });
        jPanel3.add(txtSec, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 130, 30));

        txtDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Civil Engineriering", "Rural Engineering ", "Town Planing", "Land Survaying" }));
        txtDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepActionPerformed(evt);
            }
        });
        jPanel3.add(txtDep, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 130, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 88, 150, 500));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Search A Student By Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 116, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 136, 171, 40));

        jButton8.setText("SEARCH");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(357, 136, 72, 40));

        admin1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        admin1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "LID", ".", ".", ".", ".", ".", "."
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(admin1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 182, 630, 150));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel1.setText("Copy and Place Lecturer ID number Here");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 149, -1));

        jButton10.setText("Validate");
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jButton11.setText("Delet");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 90, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel11.setText("Q1. List of Students  Registerd");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel13.setText("Q2. List of Student Per Department");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel15.setText("Q3. List of Female Student  Per Department");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel16.setText("Q4. List of Male Student  Per Departmen");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, 20));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel17.setText("Q5. List of Lecturer for Given Cycle");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel18.setText("Q6. List of Student or a Given Department");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel12.setText("Q7. Statistics of Enrollment by Class, Department, Cycle");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 500, -1, -1));

        jButton13.setText("BACK");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        jButton12.setText("JAdminS");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, -1, -1));

        jButton9.setText("Print");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 100, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon("A:\\Project 2021.2022.sim1\\SDT\\bg_035.jpg")); // NOI18N
        jLabel14.setText(" ");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 670, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       int c=0;
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT sector.ID, studentinfo.surname, studentinfo.sex, sector.Sector, sector.Document, sector.SValidation, application.Signature FROM (User INNER JOIN (studentinfo INNER JOIN sector ON studentinfo.ID = sector.SID) ON User.LOID = studentinfo.LOID) INNER JOIN application ON sector.ID = application.AIID");
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
 
                                 v2.add(rs.getInt("sector.ID"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 v2.add(rs.getString("sector.sector"));
                                 v2.add(rs.getString("sector.Document"));
                                 v2.add(rs.getInt("sector.SValidation"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }
  
  
  


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            int c=0;
        String cy = txtSec.getSelectedItem().toString();
        String cm = txtDep.getSelectedItem().toString();
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT sector.ID, studentinfo.Surname, studentinfo.sex, sector.Sector, sector.Department, sector.Document\n" +"FROM User INNER JOIN (studentinfo INNER JOIN sector ON studentinfo.ID = sector.SID) ON User.LOID = studentinfo.LOID\n" +"WHERE (((slecture.Cycle)= ?) AND ((sector.Department)= ?))");
                pst.setString(1, cy);
                pst.setString(2, cm);
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
 
                                 v2.add(rs.getInt("slecture.ID"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 v2.add(rs.getString("slecture.Cycle"));
                                v2.add(rs.getString("slecture.Document"));
                                 v2.add(rs.getInt("slecture.VLecturer"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }





        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        MessageFormat header = new MessageFormat("YouNiversity");
        MessageFormat footer = new MessageFormat("page(0, number, integer)");
         try{
             admin1.print(JTable.PrintMode.NORMAL, header, footer);
             
         }catch(Exception  e){
             JOptionPane.showMessageDialog(this, "e");
         }
        
    


        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        JAdmin m = new JAdmin(); 
            this.hide();
            m.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        JLAdmin m = new JLAdmin(); 
            this.hide();
            m.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int c=0;
         String cy = txtDep.getSelectedItem().toString();
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT slecture.ID, studentinfo.Surname, studentinfo.sex, slecture.Department, slecture.VLecturer, application.Signature\n" +"FROM User INNER JOIN ((studentinfo INNER JOIN slecture ON studentinfo.ID = slecture.SID) INNER JOIN application ON slecture.ID = application.AIID) ON User.LOID = studentinfo.LOID\n" +"WHERE (((slecture.Department)= ?))");
                pst.setString(1, cy);
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
                                 v2.add(rs.getInt("slecture.ID"));
                                 v2.add(rs.getString("slecture.Department"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 //v2.add(rs.getString("slecture.Document"));
                                 v2.add(rs.getInt("slecture.VLecturer"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int c=0;
        String cy = txtDep.getSelectedItem().toString();
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT slecture.ID, studentinfo.Surname, studentinfo.sex, slecture.Department, slecture.VLecturer, application.Signature\n" +"FROM User INNER JOIN ((studentinfo INNER JOIN slecture ON studentinfo.ID = slecture.SID) INNER JOIN application ON slecture.ID = application.AIID) ON User.LOID = studentinfo.LOID\n" +"WHERE (((studentinfo.Surname)=\"F\") AND ((slecture.Department)= ?))");
                pst.setString(1, cy);
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
 
                                 v2.add(rs.getInt("slecture.ID"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 v2.add(rs.getString("slecture.Department"));
                                // v2.add(rs.getString("slecture.Document"));
                                 v2.add(rs.getInt("slecture.VLecturer"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            int c=0;
        String cy = txtDep.getSelectedItem().toString();
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT slecture.ID, studentinfo.Surname, studentinfo.sex, slecture.Department, slecture.VLecturer, application.Signature\n" +"FROM User INNER JOIN ((studentinfo INNER JOIN slecture ON studentinfo.ID = slecture.SID) INNER JOIN application ON slecture.ID = application.AIID) ON User.LOID = studentinfo.LOID\n" +"WHERE (((studentinfo.Surname)=\"M\") AND ((slecture.Department)= ?))");
                pst.setString(1, cy);
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
 
                                 v2.add(rs.getInt("slecture.ID"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 v2.add(rs.getString("slecture.Department"));
                                // v2.add(rs.getString("slecture.Document"));
                                 v2.add(rs.getInt("slecture.VLecturer"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecActionPerformed

        String cy = txtSec.getSelectedItem().toString();
      
       

        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecActionPerformed

    private void txtDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepActionPerformed
        // TODO add your handling code here:
        String usersection = txtSec.getSelectedItem().toString();
        String userdepartment = txtDep.getSelectedItem().toString();

    }//GEN-LAST:event_txtDepActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int c=0;
        String cy = txtSec.getSelectedItem().toString();
                 try {

                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studm","root","");
                pst = con.prepareStatement("SELECT slecture.ID, studentinfo.Surname, studentinfo.sex, slecture.Cycle, slecture.VLecturer, application.Signature\n" +"FROM User INNER JOIN ((studentinfo INNER JOIN slecture ON studentinfo.ID = slecture.SID) INNER JOIN application ON slecture.ID = application.AIID) ON User.LOID = studentinfo.LOID\n" +"WHERE (((slecture.Cycle)= ?))");
                pst.setString(1, cy);
                rs = pst.executeQuery();
                rss = rs.getMetaData();
                c = rss.getColumnCount();
                c = c+1;
                Df = (DefaultTableModel)admin1.getModel();
                Df.setRowCount(0);
                while(rs.next())
                 {
                             Vector v2 = new Vector();
                             for (int j =0; j<= c; j++)
                             {
 
                                 v2.add(rs.getInt("slecture.ID"));
                                 v2.add(rs.getString("studentinfo.surname"));
                                 v2.add(rs.getString("studentinfo.sex"));
                                 v2.add(rs.getString("slecture.Cycle"));
                                // v2.add(rs.getString("slecture.Document"));
                                 v2.add(rs.getInt("slecture.VLecturer"));
                                 v2.add(rs.getString("application.Signature"));
                                 
                                 
                                 
                             }
                             Df.addRow(v2);
                        
                 }
            }catch (ClassNotFoundException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JSAdmin.class.getName()).log(Level.SEVERE, null, ex);
            }catch (NumberFormatException ex){
                ex.printStackTrace();
            }


        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JSAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JSAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable admin1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox<String> txtDep;
    private javax.swing.JComboBox<String> txtSec;
    // End of variables declaration//GEN-END:variables
}
